version: "3.7"
services:
  database:
    restart: always
    image: postgres:10.1
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - database_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - back-end

  app:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    image: happy-dogs-app
    volumes:
      - .:/happy-dogs-app
      - static_volume:/happy-dogs-app/staticfiles/
    depends_on:
      - database
    entrypoint: ["/bin/bash", "-c", "/happy-dogs-app/docker/start_app.sh"]
    stdin_open: true
    tty: true
    networks:
      - back-end
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DEBUG=${DEBUG}
      - DB_NAME=${DB_NAME}
      - DB_HOST=database
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOST=${ALLOWED_HOST}

  proxy:
    image: happy-dogs-nginx
    build:
      context: .
      dockerfile: nginx/nginx.Dockerfile
    ports:
      - "80:80"
    networks:
      - back-end
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/happy-dogs-app/static/
    restart: always
networks:
  back-end:

volumes:
    static_volume:
    database_volume:
